name: "Github action chain"
author: "Enrique Mingorance Cano <emingora@redhat.com>"
description: "GitHub action to define action chains"
inputs:
  parent-dependencies:
    description: "the list of parent project dependencies separated by comma. Something like lienzo-core,lienzo-tests"
    required: false
  child-dependencies:
    description: "the list of child project dependencies separated by comma. Something like appformer,kiegroup/droolsjbpm-build-bootstrap,drools"
    required: false
  build-command:
    description: "the list of commands as string split by | to run"
    required: true
  build-command-upstream:
    description: "the list of commands as string split by | to run in case the project is upstream built"
    required: false
  workflow-file-name:
    description: "the file flow file name, normally the same one where the flow is stored. Like `pull_request.yml`"
    required: true
  matrix-variables:
    description: "the map of matrix-variable-key:matrix-variable-value in case you want to use them from build-command/build-command-upstream.."
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "link"
  color: "purple"
