name: "Github action chain"
author: "Enrique Mingorance Cano <emingora@redhat.com>"
description: "GitHub action to define action chains"
inputs:
  buildchainversion:
    description: "the open JDK version"
    required: true
  parent-dependencies:
    description: "the list of parent project dependencies separated by comma. Something like lienzo-core,lienzo-tests"
    required: false
  child-dependencies:
    description: "the list of child project dependencies separated by comma. Something like appformer,kiegroup/droolsjbpm-build-bootstrap,drools"
    required: false
  build-command:
    description: "the list of commands as string split by | to run"
    required: true
  build-command-upstream:
    description: "the list of commands as string split by | to run in case the project is upstream built"
    required: false
runs:
  using: "docker"
  image: "docker://ginxo/github-action-build-chain:${{ inputs.buildchainversion }}"
branding:
  icon: "link"
  color: "purple"
