name: "Github action build chain. Cross-repo builds"
author: "Enrique Mingorance Cano <emingora@redhat.com>"
description: |
  Github action build chain is a tool for github actions to build multiple projects from different repositories in a single action. This tool is trying to solve the problem when a project depends on another project (most probably from the same organization) and one change can/should be performed in different repositories. How can we assure one specific pull request will work with the latest changes from/in the dependant/dependency projects and it won't break something? This is what we call cross-repo pull requests and build-chain is the way we have to solve it.
inputs:
  parent-dependencies:
    description: "the list of parent project dependencies separated by comma. Something like lienzo-core,lienzo-tests"
    required: false
  child-dependencies:
    description: "the list of child project dependencies separated by comma. Something like appformer,kiegroup/droolsjbpm-build-bootstrap,drools"
    required: false
  build-command:
    description: "the list of commands as string split by | to run"
    required: true
  build-command-upstream:
    description: "the list of commands as string split by | to run in case the project is upstream built"
    required: false
  workflow-file-name:
    description: "the file flow file name, normally the same one where the flow is stored. Like `pull_request.yml`"
    required: true
  matrix-variables:
    description: "the map of matrix-variable-key:matrix-variable-value in case you want to use them from build-command/build-command-upstream.."
    required: false
  archive-artifacts-path:
    description: "A file, directory or wildcard pattern that describes what to upload"
    required: false
  archive-artifacts-name:
    description: "Artifact name"
    default: "artifact"
    required: false
  archive-artifacts-if-no-files-found:
    description: >
      The desired behavior if no files are found using the provided path.

      Available Options:
        warn: Output a warning but do not fail the action
        error: Fail the action with an error message
        ignore: Do not output any warnings or errors, the action does not fail
    default: "warn"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "box"
  color: "red"
