name: "Github action chain"
author: "Enrique Mingorance Cano <emingora@redhat.com>"
description: "GitHub action to define action chains"
inputs:
  openjdkversion:
    description: "the open JDK version"
    required: true
    default: '8'
  parent-dependencies:
    description: "the list of parent project dependencies separated by comma. Something like lienzo-core,lienzo-tests"
    required: false
  child-dependencies:
    description: "the list of child project dependencies separated by comma. Something like appformer,kiegroup/droolsjbpm-build-bootstrap,drools"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.openjdkversion }}
branding:
  icon: "link"
  color: "purple"
